apiVersion: v1
kind: Service
metadata:
  name: {{ include "gridproxy.fullname" . }}-rmb
  labels:
    {{- include "gridproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8051
      targetPort: 8051
      protocol: TCP
      name: rmb
  selector:
    {{- include "gridproxy.selectorLabels" . | nindent 4 }}
