# name: Release action

# on:
#   release:
#     types: [published]
#     branches: [ main, development ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.17

#     - name: Build
#       run: |
#         export PATH=/home/runner/go/bin:$PATH
#         export GIT_COMMIT=$(git rev-list -1 HEAD) 
#         go build -ldflags "-X main.GitCommit=$GIT_COMMIT" cmds/proxy_server/main.go 
# #what does -x main.gitcommit=$git_commit mean
#       env:
#         GO111MODULE: on



  
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  releaseandpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
